<div class="form-add">
  <h2><?php echo $this->__('Write Your Review') ?></h2>
  <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
    <?php echo $this->getBlockHtml('formkey'); ?>
      <fieldset>
        <?php echo $this->getChildHtml('form_fields_before') ?>
        
        
        <div class="rev-product-info">
       <!--------------------------- By Ravi ---------------------------------------------------------------------------------------->
        <span><img id="prodimg" src="<?php echo $this->helper('catalog/image')->init($this->getProductInfo(), 'small_image')->resize(225, 225);?>"></span>        <!-------------------------------------------------------------------------------------------------------------------------->
       <?php /*?> <h3><?php echo $this->__("You're reviewing:"); ?> <?php */?><h2><span><?php echo $this->htmlEscape($this->getProductInfo()->getName()) ?></span></h2>
       <!--------------------------- By Ravi ---------------------------------------------------------------------------------------->
       <h3><span><?php echo $this->htmlEscape($this->getProductInfo()->getDescription()) ?></span></h3>
       <button class="white">Read more</button>
               <!-------------------------------------------------------------------------------------------------------------------------->
		</div>

        <?php if ($this->getRatings() && $this->getRatings()->getSize()): ?>
          <h4><?php echo $this->__('Choose your product ratings') ?> <em class="required">*</em></h4>
          <span id="input-message-box"></span>


          <?php if (Mage::helper('ActiveReviewStars')->getReviewStarMode() == 1) { ?>
            <table class="data-table" id="product-review-table">
              <col width="1" />
              <col width="5" />
             
              <tbody>
              
                <?php  foreach ($this->getRatings() as $_rating): ?>
                  <tr>
                    <td><?php echo $this->escapeHtml($_rating->getRatingCode()) ?><br/>
                    <span class="value">
                      <?php foreach ($_rating->getOptions() as $_option): ?>
                        <input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio star" />
                      <?php endforeach; ?>
                    </span></td>
                  </tr>
                <?php endforeach; ?>
              </tbody>
            </table>
          <?php }else { ?>
            <table class="data-table" id="product-review-table">
              <tbody>
                <tr>
                  <td>
                    <?php foreach ($this->getRatings() as $_rating): ?>
                      <span class="star-rating-box">
                        <?php if (Mage::helper('ActiveReviewStars')->showRatingLabel()) { ?>
                          <span class="star-rating-label"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?>:</span>
                        <?php } ?>

                        <?php foreach ($_rating->getOptions() as $_option): ?>
                          <input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio star" />
                        <?php endforeach; ?>
                      </span>
                    <?php endforeach; ?>
                  </td>
                </tr>
              </tbody>
            </table>
          <?php } ?>

          <input type="hidden" name="validate_rating" class="validate-rating" value="" />
          <script type="text/javascript">decorateTable('product-review-table')</script>
        <?php endif; ?>
        <p><input type="range" name="rangeInput" id="ran" max="5" min="1" step="1" oninput="updateTextInput(this.value);"><label id="textInput"></label></p>
        <p> <label >Do you recommend this product?</label><br>
                <input type="radio" name="recommend" value="Yes">Yes<br>
                <input type="radio" name="recommend" value="No">No</p>
        <h4><?php echo $this->__('Leave your review') ?><em class="required">*</em></h4>
        <ul class="form-list">
        <fieldset class="rev">
           <li class="inline-label">
                        <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Review Summary') ?></label>
                        <div class="input-box">
                            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" />
                        </div>
                   </li>
                   
          <li>
                        <label for="review_field" class="required"><em>*</em><?php echo $this->__('Your Review') ?></label>
                        <div class="input-box">
                            <textarea name="detail" id="review_field" cols="7" rows="9" class="required-entry input-text"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                        </div>
         </li>
         
          <div class="guidelines">
                    <h6>Writing Guidelines:</h6>
                    <p>We want to publish your review, so please:</p>
                    <ul>
                        <li>- Keep your review focused on the product</li>
                        <li>- Avoid writing about customer service;contact us instead if you have issues requiring immediate attention</li>
                        <li>- Refrain from mentioning competitors or the specific price you paid for the product</li>
                        <li>- Do not include any personally identifiable information, such as full names</li>
                    </ul>
            </div>
            </fieldset>
         <h4><?php echo $this->__('Optional: Share relevant photos and video') ?><em class="required">*</em></h4>
                 <fieldset class="mediarev">                  
                    <div class="image">
                    <li>
                        <label for="reviewimage" class=""><!--<em>*</em>--><?php echo $this->__('Upload Your Images') ?></label>
                        <div class="input-box">
                            <input type="file" name="reviewimage" id="revfile" class="input-text required-entry"  onchange="pressed()"/>
                            <label id="fileLabel">No Files Chosen</label>
                        </div>
                
                    </li>
                    <p><button id="upload" title="<?php echo $this->__('Upload')?>"  ><span><span><?php echo $this->__('Upload')?></span></span></button></p>
                    </div>
                    <div class="video">
                    <label for="video_field"><?php echo $this->__('Link to your video') ?></label>
                         <div class="input-box">
                            <input type="text" name="video_field" id="video_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getVideolink()) ?>" />
                        </div>
                    <label for="caption_field"><?php echo $this->__('Caption') ?></label>
                         <div class="input-box">
                            <input type="text" name="caption_field" id="caption_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getCaption()) ?>" />
                        </div>

                    </div>
                 <div class="guidelines">
                    <h6>Media Guidelines:</h6>
                    <p>We want to publish your review, so please:</p>
                    <ul>
                        <li>- Upload media related to the product.</li>
                        <li>- Confirm you hold the copyright for the media.</li>
                        <li>- Images must be atleast 533 in width and height.</li>
                    </ul>
            </div>
            </fieldset>

           <h4><?php echo $this->__('Include related products') ?><em class="required">*</em></h4>
           
           <fieldset class="relprod">
           
           <p>What products do you recommend? Add them to your review.</p>
           <p><button id="addprod" title="<?php echo $this->__('Add Product')?>"  ><span><span><?php echo $this->__('Add Product')?></span></span></button></p>
           
           </fieldset>
           
            <h4><?php echo $this->__('Your information') ?><em class="required">*</em></h4>
            
             <fieldset class="userinfo" >
             <div class="maindiv">
                   <div class="lefttf">
                    <li class="inline-label">
                        <label for="nickname_field" class="required"><em>*</em><?php echo $this->__("Your Nickname?") ?></label>
                        <div class="input-box">
                            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" />
                        </div>
                    </li>
                    
                    <li class="inline-label">
                        <label for="city_field" class="required"><em>*</em><?php echo $this->__("Your city ") ?></label>
                        <div class="input-box">
                            <input type="text" name="city" id="city_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getCity()) ?>" />
                        </div>
                    </li>
                    
                    <li class="inline-label">
                        <label for="email_field" class="required"><em>*</em><?php echo $this->__("Your Email ") ?></label>
                        <div class="input-box">
                            <input type="text" name="email" id="email_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getEmail()) ?>" />
                        </div>
                    </li>
                    
                    </div>
                    
                    <div class="righttf">
                    
                     <li class="inline-label">
                        <label for="state_field" class="required"><em>*</em><?php echo $this->__("Your State ") ?></label>
                        <div class="select-box">
              	            <select>
                            	<option name="state" value="<?php echo $this->escapeHtml($data->getState()) ?>">India</option>
                                <option name="state" value="<?php echo $this->escapeHtml($data->getState()) ?>">Singapore</option>
                            </select>
                        </div>
                     </li>   
                     
                      <li class="inline-label">
                        <label for="age_field" class="required"><em>*</em><?php echo $this->__("How old are you? ") ?></label>
                        <div class="select-box">
 							<select>
                    			<option value=""></option>
                    			<option value="under18">Under 18</option>
                    			<option value="18-24">18-24</option>
                    			<option value="25-34">25-34</option>
                    			<option value="35-44">35-44</option>
                    			<option value="45-54">45-54</option>
                    			<option value="55-64">55-64</option>
                    			<option value="over65">Over 65</option>
               		 		</select>                        
                     	</div>
                     </li>
                     
                     <li class="inline-label">
                        <label for="age_field" class="required"><em>*</em><?php echo $this->__("What type of rider are you? ") ?></label>
                        <div class="select-box">
 							<select>
                        		<option value=""></option>
                        		<option value="adventurer">Adventurer</option>
                        		<option value="kneedragger">Kneedragger</option>
                        		<option value="dirtmaven">Dirt Maven</option>
                    		</select>
                     	</div>
                     </li>
                     </div>
                     </div >
                     <div class="below1">
                       <li class="inline-label">
                        <label style="float:left" for="gender_field"><?php echo $this->__("Gender ") ?></label>
                        <div  class="radio-box">
 							<input type="radio" name="gender" value="Male"> Male
               				<input type="radio" name="gender" value="Female"> Female
                     	</div>
                     </li>
                     
                     <input type="checkbox" name="email" value="post"><label for="c1"> Please send me an email when my review is posted</label><br>
                	 <input type="checkbox" name="email" value="comment"> Please send me an email when someone comments on my review<br>
                	 <label name="email" class="required" ><em>*</em>Your email address</label><br>
                	 <input type="email" name="email" class="input-text required-entry">
                     
                     </div>
                     </fieldset>
                     <h4><?php echo $this->__('Add additional feedback to customer service') ?><em class="required">*</em></h4>
                     
                     <fieldset class="revfeedback">
                     <li class="inline-label">
                     	<label for="customer_field" name="crecom"><?php echo $this->__("Would you recommend BIKEFIXR to a friend?") ?></label>
                      <p>  <input type="radio" name="crecom" value="no">  No
                    	<input type="radio" name="crecom" value="maybe">  Maybe
                    	<input type="radio" name="crecom" value="definitely">  Definitely
                        </p>
          			</li>
                    
                    <li class="inline-label">
                    	<p><label for="customer_field" name="why"><?php echo $this->__("Please tell us why?") ?></label><br>
                    <textarea name="why" class="input-text" rows="5" cols="100"></textarea>
                </p>
                
                </li>
                </fieldset>
        </ul>
      </fieldset>
      <div class="buttons-set">
      <p><button title="<?php echo $this->__('Preview')?>"  ><span><span><?php echo $this->__('Preview')?></span></span></button>
            <button title="<?php echo $this->__('Cancel')?>"  ><span><span><?php echo $this->__('Cancel')?></span></span></button>
        <button type="submit" title="<?php echo $this->__('Submit Review') ?>" ><span><span><?php echo $this->__('Submit') ?></span></span></button></p>
      </div>
    </form>
    <script type="text/javascript">
      //<![CDATA[
      var dataForm = new VarienForm('review-form');
      Validation.addAllThese(
      [
        ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
            var trs = $('product-review-table').select('tr');
            var inputs;
            var error = 1;

            for( var j=0; j < trs.length; j++ ) {
              var tr = trs[j];
              <?php if (Mage::helper('ActiveReviewStars')->getReviewStarMode() == 2) { ?>
                if( j >= 0 ) {
              <?php }else{ ?>
                  if( j > 0) {
              <?php } ?>
                inputs = tr.select('input');
                for( i in inputs ) {
                  if( inputs[i].checked == true ) {
                    error = 0;
                  }
                }
                  
                if( error == 1 ) {
                  return false;
                } else {
                  error = 1;
                }
              }
            }
            return true;
          }]
      ]
    );
      //]]>
    </script>
  <?php else: ?>
    <p class="review-nologged" id="review-form">
      <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
  <?php endif ?>
</div>
