<?php
/**
 * Layered Navigation Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Nav
 * @version      2.6.1
 * @license:     lOeKpIO8WfhJjGJEKeiy8x6dx2Qzsqo8LrDiR2B3nm
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
    <?php if($this->isHomePage()) :?>
        var lookhomepage = 1;
    <?php else :?>
        var lookhomepage = 0;
    <?php endif;?>
</script>