<?php
/**
 * Layered Navigation Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Nav
 * @version      2.6.1
 * @license:     lOeKpIO8WfhJjGJEKeiy8x6dx2Qzsqo8LrDiR2B3nm
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
if(Mage::helper('adjnav')->isModuleEnabled('Aitoc_Aitmanufacturers')):?>
<script type="text/javascript">
var currentShopByAttribute = "<?php echo Mage::registry('shopby_attribute');?>";
var currentShopByAttributeValue = "<?php echo Mage::getSingleton('core/session')->getAitocManufacturersCurrentManufacturerId();?>";
</script>
<?php endif;?>