<?php 
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
$current_user_mail= Mage::getSingleton('customer/session')->getCustomer()->getEmail();
$current_user_name= Mage::getSingleton('customer/session')->getCustomer()->getName();
$current_user_phone= Mage::getSingleton('customer/session')->getCustomer()->getPrimaryBillingAddress()->getTelephone();
}
?>
<div id="box">
<form id="bikefixr_returnorder_form" name="bikefixr_returnorder_form" action="<?php echo $this->getUrl('feedback/');?>index/sendemailReturnOrder" method="post">
    <fieldset class="group-select">
        <div class="input-box">
            <label for="orderno">Your Order No: <span></span></label>
            <br />
            <input class="cs-input-disable" name="orderno" id="orderno" title="orderno" value="" type="text" />
        </div>
        <div class="input-box">
       <label for="itemname">Item Name: <span></span></label>
          <br />
            <input class="cs-input-disable" name="itemname" id="itemname" title="itemname" value="" type="text" />
        </div> 
        <div class="input-box">
            <label for="username">Full Name: <span></span></label>
            <br />
            <input <?php if($current_user_name){echo 'class="cs-input-disable"';} ?> type="text" name="username" value="<?php echo $current_user_name ?>" />
        </div>
        <div class="input-box">
            <label for="email">E-mail: <span></span></label>
            <br />
            <input class="input-text validate-email required-entry <?php if($current_user_mail){echo ' cs-input-disable';} ?>" type="email" name="email" value="<?php echo $current_user_mail ?>" />
        </div>
        <div class="input-box">
            <label for="phone">Phone-Number: <span></span></label>
            <br />
            <input <?php if($current_user_phone){echo 'class="cs-input-disable"';} ?> type="text" name="phone" value="<?php echo $current_user_phone ?>" />
        </div>


        <label>Select Reason For Return Order:</label>
        <select id="select-option" name="reason">
            <option value="0">--Reason For Returning Item--</option>
            <option value="I want to change the payment Method">I want to change the payment Method</option>
            <option value="I am not sure this product will be delivered in time">I am not sure this product will be delivered in time</option>
            <option value="I have no money now">I have no money now</option>
        </select>

        <div class="input-box">
            <label for="user-msg">Comment</label>
            <br />
            <textarea name="user-msg" id="user-msg" title="user-msg" style="height:100px;" cols="50" rows="3"></textarea>
        </div>
    </fieldset>

    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button class="form-button cs-red" type="submit"><span>Submit</span></button>
    </div>


</form>
</div>

<script>

myform=new VarienForm('bikefixr_returnorder_form',false);

var parentOrderno = document.getElementById("orderno");
parentOrderno.value = parent.car.ordernum;
 var parentItem = document.getElementById("itemname");
parentItem.value = parent.car.itemname;

Event.observe('bikefixr_returnorder_form', 'submit', function(event) {
	results=myform.validator.validate();
	if(results){
    $('bikefixr_returnorder_form').request({
		
        onFailure:failureFunc,
        onSuccess:successFunc
    });
    Event.stop(event); // stop the form from submitting
	}
});

 function successFunc(response){
   
     if (200 == response.status){
        //alert("Call is success");
    }
    var container = $('box');
    var content = response.responseText; 
    container.update(content);
	//alert('Mail sent');
	//jQuery.fancybox.close();
}

function failureFunc(response){

    var container = $('box');
    var content = response.responseText;
    container.update(content);
}


</script>